"""empty message

Revision ID: 4afd636db8bd
Revises: fb3e699b466b
Create Date: 2020-08-14 10:03:16.161638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afd636db8bd'
down_revision = 'fb3e699b466b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'created_at')
    # ### end Alembic commands ###
