"""empty message

Revision ID: fb3e699b466b
Revises: c4f183bbde8f
Create Date: 2020-08-14 09:53:51.789988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb3e699b466b'
down_revision = 'c4f183bbde8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'meta')
    # ### end Alembic commands ###
